# Generated by Django 3.1.5 on 2021-01-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('main_gun', models.CharField(max_length=256)),
                ('side_gun', models.CharField(max_length=256)),
                ('skins', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('platform', models.CharField(max_length=128)),
                ('lang', models.CharField(max_length=6)),
                ('browser', models.CharField(max_length=256)),
                ('screen_width', models.IntegerField(default=-1)),
                ('screen_height', models.IntegerField(default=-1)),
                ('referrer', models.CharField(max_length=512, null=True)),
                ('has_touchscreen', models.BooleanField(default=False)),
                ('has_ad_blocker', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(default=-1)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('auth', models.BooleanField(default=False)),
                ('level', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('inventory_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.userinventory')),
            ],
            options={
                'verbose_name': 'Gioele User',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('shooted_primary', models.IntegerField()),
                ('shooted_secondary', models.IntegerField()),
                ('killed', models.IntegerField()),
                ('powerups', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guser')),
            ],
        ),
    ]
