# Generated by Django 3.1.5 on 2021-02-01 21:37

import api.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.CharField(default=api.utils.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'main'), (1, 'side')])),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=128)),
                ('cooldown', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('max_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('auth', models.BooleanField(default=False, verbose_name='Email authentication completed')),
                ('level', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Gioele User',
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.CharField(default=api.utils.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_guns', models.CharField(default=None, max_length=256, null=True)),
                ('side_guns', models.CharField(default=None, max_length=256, null=True)),
                ('skins', models.CharField(default=None, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=16)),
                ('platform', models.CharField(max_length=128)),
                ('lang', models.CharField(max_length=6)),
                ('browser', models.CharField(max_length=256)),
                ('screen_width', models.IntegerField(default=-1)),
                ('screen_height', models.IntegerField(default=-1)),
                ('referrer', models.CharField(max_length=512, null=True)),
                ('has_touchscreen', models.BooleanField(default=False)),
                ('has_ad_blocker', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('exp_gained', models.IntegerField()),
                ('coins_earned', models.IntegerField()),
                ('shooted_primary', models.IntegerField()),
                ('shooted_secondary', models.IntegerField()),
                ('killed', models.CharField(max_length=128)),
                ('powerups', models.CharField(max_length=128)),
                ('skin', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guser')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visitlog')),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guser')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.visitlog')),
            ],
        ),
        migrations.AddField(
            model_name='guser',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.userinventory'),
        ),
    ]
