# Generated by Django 3.1.5 on 2021-02-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchLog',
        ),
    ]
