# Generated by Django 3.1.5 on 2021-01-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guser',
            old_name='inventory_id',
            new_name='inventory',
        ),
    ]
