# Generated by Django 3.1.7 on 2021-03-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210307_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselog',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guser'),
        ),
    ]
