# Generated by Django 3.1.5 on 2021-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210202_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchlog',
            old_name='shooted_primary',
            new_name='shooted_main',
        ),
        migrations.RenameField(
            model_name='matchlog',
            old_name='shooted_secondary',
            new_name='shooted_side',
        ),
        migrations.AddField(
            model_name='gun',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
