# Generated by Django 3.1.5 on 2021-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210130_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='main_gun',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='side_gun',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='skins',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
