# Generated by Django 3.1.5 on 2021-02-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210211_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchLog',
            new_name='GameLog',
        ),
    ]
