# Generated by Django 3.1.6 on 2021-02-24 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_purchaselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by', to=settings.AUTH_USER_MODEL),
        ),
    ]
