# Generated by Django 3.1.5 on 2021-02-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210211_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='coins_earned',
            new_name='gbucks_earned',
        ),
    ]
