# Generated by Django 3.1.5 on 2021-01-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210130_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'main'), (1, 'side')])),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=128)),
                ('cooldown', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('max_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
    ]
