# Generated by Django 3.1.5 on 2021-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210211_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='guser',
            name='skin',
            field=models.CharField(default='', max_length=4),
        ),
    ]
