# Generated by Django 3.1.5 on 2021-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_guser_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
