# Generated by Django 3.1.5 on 2021-01-30 14:04

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210130_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='id',
            field=models.CharField(default=api.utils.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skin',
            name='id',
            field=models.CharField(default=api.utils.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
    ]
