# Generated by Django 3.1.5 on 2021-01-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210130_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinventory',
            old_name='main_gun',
            new_name='main_guns',
        ),
        migrations.RenameField(
            model_name='userinventory',
            old_name='side_gun',
            new_name='side_guns',
        ),
    ]
