from api.classes import Parser

DELAY_BETWEEN_ENEMIES_GENERATIONS = 5 # in seconds
MAX_MSHIP_LIFES = 3
POWERUPS_LAST_TIME = 10 # in seconds
CLIENT_CANVAS_WIDTH = 800 # in pixels
CLIENT_MAX_CANVAS_DEPTH = 300 # in pixels
ENEMIES_PER_GENERATION = 5
